---
title: "Course Schedule"
toc: false
---

Course content is designed to be flexible to accommodate student interest and abilities. 


| Date    |  Title     | Description |  
|:--|:---------|:---------------------------------------------|
| Thurs, Jan 26  |   **Introduction** |  |   
| Thurs, Feb 1   |   **Global Environmental and Biodiversity Information** |  |   
| Thurs, Feb 8   |  **Spatial Modelling in R - an introduction** | We'll use spatial data to introduce fundamental concepts for the R programming language and teach best coding practices useful for beginners and experienced alike. Goals include: (1) Experience useful for future, more specific workshops with BGC; (2) Setting up a workflow to make sure coding isn't annoying; (3) Loops; (4) Writing functions; (5) Using raster (spatial) data; (6) Customizable pretty plots.|   
| Thurs, Feb 15 |  **Modelling species distributions in R** | We’ll use a complete workflow – from data download to pretty maps of predictions – to model a species geographic distribution (range). Goals include learning how to use:(1) Understand modeling decisions; (2) Statistical regression techniques; (3) Machine learning techniques; (4) Manipulate rasters; (5) Customize plots; (6) Write a workflow that others can use.|
| Thurs, Feb 22   |  **Modeling marine biodiversity distributions** |  |   
| Thurs, Mar 1   |  **Macroecology and spatial biodiversity science** |  |   
| Thurs, Mar 8   | **Biodiversity and Global Change** |  |   
| Thurs, Mar 29   | **Modelling animal migrations** |  |   
| Thurs, Apr 5  |   **Modelling diversity change** |  |   
| Thurs, Apr 12   | **The evolutionary underpinning of species distributions** |  |   
| Thurs, Apr 19  |   **Capturing species population change** |  |   
| Thurs, Apr 26  |   **Projecting biodiversity change** |  |   
| Thurs, May 2   |   **Biodiversity Movement and Global Change Symposium** |  |   


